// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconDelete: typeof import('./components/IconDelete.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    TodoActive: typeof import('./components/TodoActive.vue')['default'];
    TodoAll: typeof import('./components/TodoAll.vue')['default'];
    TodoDone: typeof import('./components/TodoDone.vue')['default'];
    TodoList: typeof import('./components/TodoList.vue')['default'];
  }
}

export {};
